### ISSUE TITLE
Request: Support Compatibility with OpenTofu + `tenv`

### ISSUE THREAD

**Issue by RDhar** [DevSecTop/TF-via-PR-Comments#140]
#### Is your feature request related to a problem

N/a. 

#### Describe the solution you'd like

With the launch of [OpenTofu fork](https://github.com/opentofu/opentofu), I'd like to support OpenTofu as a first-class IaC provisioning tool, just like Hashicorp's Terraform.

#### Describe alternatives you've considered

While we await (pre-)releases to become available, a serviceable workaround has been shared by @zimeg (from [Slack](https://opentofucommunity.slack.com/archives/C05QF5HA0BH/p1695507933533049?thread_ts=1695420789.157869&cid=C05QF5HA0BH)) to download, install and initialize OpenTofu CLI in 3 GitHub Actions steps.

```yaml
- name: Download the tofu source
  uses: actions/checkout@v4
  with:
    repository: opentofu/opentofu
    path: opentofu

- name: Install tofu tooling
  uses: actions/setup-go@v4
  with:
    go-version-file: opentofu/go.mod
    cache-dependency-path: opentofu/go.sum

- name: Prepare the tofu command
  working-directory: opentofu
  run: |
    go build -ldflags "-w -s -X 'github.com/opentofu/opentofu/version.dev=no'" -o bin/tofu .
    echo $(pwd)/bin >> $GITHUB_PATH
```

#### Additional context

Issue https://github.com/opentofu/opentofu/issues/556 has been raised in order to deliver a more "drop-in replacement"-able equivalent to [hashicorp/setup-terraform](https://github.com/hashicorp/setup-terraform).
